config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :user do
    resources :flights
  end

  resources :charges

  root 'welcome#index'
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :flight_time, presence: true
  validates :checkin_time, presence: true
  validates :confirmation_number, presence: true
  belongs_to :user

  before_validation :set_checkin
  after_save :set_async
  after_save :send_new_flight_email

  private

  def set_checkin
    self.checkin_time = self.flight_time.prev_day if self.flight_time
  end

  def set_async
    FlightWorker.perform_at(scheduled_at, self.id)
  end

  def scheduled_at
    self.checkin_time.to_time.to_i - Time.now.to_i
  end

  def send_new_flight_email
    FlightsMailer.new_flight_email(self).deliver
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  def index
    @flights = Flight.where(user: current_user)
    # if @flights.length == 0
    #   flash[:alert] = "You have no upcoming flights, create one to get started"
    # end
  end

  def show
  end

  def new
    @flight = Flight.new
  end

  def edit
  end

  def create
    @flight = Flight.new(flight_params)
    Time.zone = @flight.timezone
    @flight.user = current_user
    @flight.flight_time = Time.zone.parse(flight_params[:flight_time])
    respond_to do |format|
      if @flight.save
        format.html { redirect_to user_flights_url, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        p @flight.errors
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to user_flights_url, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to user_flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_flight
      @flight = Flight.find(params[:id])
    end

    def flight_params
      params.require(:flight).permit(:flight_time, :confirmation_number, :flight_number, :timezone)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper

  def automatic_checkin(flight_object)
    page = Mechanize.new.get "https://www.southwest.com/"
    form = page.form_with(:name => "homepage-booking-form-check-in")
    form['confirmationNumber'] = flight_object.confirmation_number
    form['firstName'] = flight_object.user.first_name
    form['lastName'] = flight_object.user.last_name
    success_page = form.submit
    success_page = success_page.content.to_s
    flight_object.update(success_page: success_page)
  end

  def flight_lookup(flight_id)
    Flight.find(flight_id)
  end
end

app/views/flights/_form.html.erb
<div class="form-container">
  <span class="form-input">
  <label class="hidden">Flight Number</label>
    <%= f.text_field :flight_number, placeholder: "Flight Number" %>
  </span>

  <span class="form-input">
  <label class="hidden">Confirmation Number</label>
  <%= f.text_field :confirmation_number, placeholder: "Confirmation Number"  %>
  </span>

  <span class="form-input">
  <label>Flight Time </label>
  <%= f.datetime_field :flight_time, class: "select" %>
  </span>

  <span class="form-input">
  <label>Time Zone </label>
  <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.all.sort, default: "Pacific Time (US & Canada)", class: "select timezone" %>
  </span>
  </div>
  
  <div class="flight-buttons">
      <%= f.submit yield(:button_text), class: 'btn-sm btn-create' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), user_flights_path(current_user), :class => 'btn-sm btn-cancel' %>
  </div>
</div>

app/views/flights/edit.html.erb
<% provide(:title, 'Edit Flight')  %>
<% provide(:button_text, 'Edit Flight')%>

<div class="title-div"><h2 class="page-header">Edit Flight</h2></div>

<%=form_for @flight, url: user_flight_path do |f|%>
  <%= render 'form', f: f %>
<% end %>

<script type="text/javascript">
  $(function () {
    $("#flight_flight_time").on("focusout", function (e) {
      flightTime = $("#flight_flight_time").val()
      var checkIn = new Date(flightTime) - 864e5
      $('#checkin-time').text(new Date(checkIn));
    });
  });
</script>

app/views/flights/index.html.erb
<%- model_class = Flight -%>
<p id="notice"><%= notice %></p>


<div class="title-div"><h2 class="page-header">Flights</h2></div>
<div class="form-container">
<table class ="table table-bordered table-hover flights-table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:flight_number)%></th>
      <th><%= model_class.human_attribute_name(:checkin_time)%></th>
      <th><%= model_class.human_attribute_name(:flight_time)%></th>
      <th><%=t '.actions', default: t("helpers.actions")%></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_number %></td>
        <td>
          <div class="time-block col-md-8">
            <span class="rendered-time"><%= flight.checkin_time.in_time_zone(flight.timezone).strftime("%I:%M%p") %></span><br />
            <%= flight.checkin_time.in_time_zone(flight.timezone).strftime("#{flight.timezone}") %>
          </div>
          <div class="date-block col-md-4">
            <span class="cal-month">
              <%= flight.checkin_time.in_time_zone(flight.timezone).strftime("%b") %>
            </span>
            <span class="cal-date">
              <%= flight.checkin_time.in_time_zone(flight.timezone).strftime("%d") %>
            </span>
          </div>
        </td>
        <td>
          <div class="row">
          <div class="time-block col-md-8">
            <span class="rendered-time"><%= flight.flight_time.in_time_zone(flight.timezone).strftime("%I:%M%p") %></span><br />
            <%= flight.flight_time.in_time_zone(flight.timezone).strftime("#{flight.timezone}") %>
          </div>
          <div class="date-block col-md-4">
            <span class="cal-month">
              <%= flight.flight_time.in_time_zone(flight.timezone).strftime("%b") %>
            </span>
            <span class="cal-date">
              <%= flight.flight_time.in_time_zone(flight.timezone).strftime("%d") %>
            </span>
          </div>
          </div>
        </td>
        <td><%= link_to '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>'.html_safe, edit_user_flight_url(current_user, flight), class: 'glyph-button', title: 'edit flight' %>
          <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>'.html_safe, user_flight_path(current_user,flight), method: :delete, class: 'glyph-button', title: 'delete flight' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<div class='flight-buttons'>
  <%= link_to 'New Flight', new_user_flight_path, class: 'btn-sm btn-create' %>
</div>

app/views/flights/new.html.erb
<% provide(:title, 'New Flight')  %>
<% provide(:button_text, 'Create Flight')%>

<div class="title-div"><h2 class="page-header">New Flight</h2></div>
<%=form_for @flight, url: user_flights_path(current_user), html: { method: :post } do |f|%>
  <%= render 'form', f: f %>
<% end %>

<script type="text/javascript">
  $(function () {
    $("#flight_flight_time").on("focusout", function (e) {
      flightTime = $("#flight_flight_time").val()
      var checkIn = new Date(flightTime) - 864e5
      $('#checkin-time').text(new Date(checkIn));
    });
  });
</script>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flight_path %>