config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :user do
    resources :flights
  end

  resources :charges

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Window Seat</title>
    <%= csrf_meta_tags %>

      <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <meta name="google-site-verification" content="17wJIvWDD3SmyhgSTORXwzEzTv0-tXtAL7iswNSqVgg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Latest compiled and minified JavaScript -->
  <script
  src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
  integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc="
  crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="shadow-container">
    <% unless controller_name == "welcome" %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <!-- responsive menu -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Window Seat</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to 'Your Flights', user_flights_url(current_user) %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
            <% else %>
              <li> <%= link_to 'Sign In', new_user_session_url %> </li>
              <li> <%= link_to 'Sign Up', new_user_registration_url %> </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <% end %>
      <div class="container">
      <%= yield %>
      </div>
      <nav class="footer navbar-fixed-bottom">
        <div class="footer-links">
          <a class="footer-link" href="#">© 2017</a>
          <a class="footer-link" href="mailto:support@windowseat.club">Support <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a>           
          <a class="footer-link" href="https://github.com/RNBrandt/WindowSeat">Code  <%= image_tag "GitHub-Mark-32px.png", alt: "GitHub logo", height: "24px" %></a>
        </div>
      </nav>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>